# coding=gbk
import re
import string
  
outFile = open('detail.xml','w+')
outFile.write('<phoneList>\n')
for i in range(605):
    inFile = open('phone\\phone'+str(i)+'\\phone'+str(i)+'.txt', 'r')
    t = inFile.read()

    print (str(i)+':')
    name=re.search('品名(?P<name>.+?)\n+?',t).group('name')
    price=re.search('参考价格(?P<price>.+?)\n+?',t).group('price')
    score=re.search('评分(?P<score>.+?)\n+?',t).group('score')
    contin=re.search('电池续航(?P<contin>.+?)\n+?',t).group('contin')
    scrnEfc=re.search('屏幕效果(?P<scrnEfc>.+?)\n+?',t).group('scrnEfc')
    photoEfc=re.search('拍照效果(?P<photoEfc>.+?)\n+?',t).group('photoEfc')
    recreation=re.search('影音娱乐(?P<recreation>.+?)\n+?',t).group('recreation')
    perfm=re.search('外观设计(?P<perfm>.+?)\n+?',t).group('perfm')
    xinjia=re.search('性价比(?P<xinjia>.+?)\n+?',t).group('xinjia')
    time=re.search('曝光日期(?P<time>.+?)\n+?',t).group('time')
    scrnSize=re.search('主屏尺寸(?P<scrnSize>.+?)\n+?',t).group('scrnSize')
    fenbian=re.search('分辨率(?P<fenbian>.+?)\n+?',t).group('fenbian')
    cpu=re.search('CPU频率(?P<cpu>.+?)\n+?',t).group('cpu')
    battery=re.search('电池容量(?P<dianchi>.+?)\n+?',t).group('dianchi')
    quality=re.search('重量(?P<quality>.+?)\n+?',t).group('quality')
    front=re.search('前摄像头(?P<front>.+?)\n+?',t).group('front')
    back=re.search('后摄像头(?P<back>.+?)\n+?',t).group('back')
    size=re.search('手机尺寸(?P<size>.+?)\n+?',t).group('size')
    url=re.search('mm\n(?P<url>.+)',t).group('url')

    outFile.write('<phone id='+str(i)+'>\n')
    outFile.write('\t<brand>'+name+'</brand>\n')
    outFile.write('\t<price>'+price+'</price>\n')
    outFile.write('\t<score>'+score+'</score>\n')
    outFile.write('\t<contin>'+contin+'</contin>\n')
    outFile.write('\t<scrnEfc>'+scrnEfc+'</scrnEfc>\n')
    outFile.write('\t<photoEfc>'+photoEfc+'</photoEfc>\n')
    outFile.write('\t<reaction>'+recreation+'</reaction>\n')
    outFile.write('\t<perfm>'+perfm+'</perfm>\n')
    outFile.write('\t<xinjia>'+xinjia+'</xinjia>\n')
    outFile.write('\t<time>'+time+'</time>\n')
    outFile.write('\t<scrnSize>'+scrnSize+'</scrnSize>\n')
    outFile.write('\t<fenbian>'+fenbian+'</fenbian>\n')
    outFile.write('\t<cpu>'+cpu+'</cpu>\n')
    outFile.write('\t<battery>'+battery+'</battery>\n')
    outFile.write('\t<quality>'+quality+'</quality>\n')
    outFile.write('\t<front>'+front+'</front>\n')
    outFile.write('\t<back>'+back+'</back>\n')
    outFile.write('\t<size>'+size+'</size>\n')
    outFile.write('\t<url>'+url+'</url>\n')
    outFile.write('</phone>\n')
    inFile.close()
outFile.write('</phoneList>\n')
outFile.close()
